<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
        http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>
    <groupId>fr.ksuto</groupId>
    <artifactId>tools</artifactId>
    <packaging>jar</packaging>
    <version>1.1</version>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <!--                    <compilerArgument>-Xlint:all</compilerArgument>-->
                    <!--                    <showWarnings>true</showWarnings>-->
                    <showDeprecation>true</showDeprecation>
                    <source>8</source>
                    <target>8</target>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <!--    <distributionManagement>-->
    <!--        <repository>-->
    <!--            <id>google-drive-repository</id>-->
    <!--            <url>file://${user.home}/google drive/maven-repository/mvn-releases</url>-->
    <!--        </repository>-->
    <!--        <snapshotRepository>-->
    <!--            <id>google-drive-snapshot</id>-->
    <!--            <url>file://${user.home}/google drive/maven-repository/mvn-snapshots</url>-->
    <!--        </snapshotRepository>-->
    <!--    </distributionManagement>-->

</project>